version: "3"

services:
  delivery_db:
    image: mysql:8.0
    restart: always
    container_name: delivery_server_db
    ports:
      - 3380:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      TZ: UTC
    volumes:
      # 바인드 마운트
      - ./data/mysql/:/var/lib/mysql




